// export const API = 'http://localhost:5000';
export const API = "http://89.43.33.70:3111";
export const AUTH_ROUTE = '/';
export const LOG_IN_ROUTE = '/log-in';
export const SETUP_ROUTE = '/setup';
export const EDIT_ROUTE = '/edit';
export const PROFILE_ROUTE = '/profile';
export const FEED_ROUTE = '/feed';
export const NOT_FOUND_ROUTE = '/not-found';